version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - "80:80"
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend/upload:/app/upload
      - ./backend/logs:/app/logs
    networks:
      - app-network
    ports:
      - "8080:8080"

  parse_fias:
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - app-network
    restart: no
    command: ["./parse_fias"]

  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: addressSchema
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: